### ISSUE TITLE
Unable to request API Key

### ISSUE THREAD

**Issue by Kosty1024Bit** [deadlock-api/deadlock-api-assets#2]
I want to get some match statistics. I go to https://deadlock-api.com/, click on the "Request API-Key" button and then the Discord page about the expired invitation opens. This is the only place where I was able to contact you.

**Comment by raimannma** [comment]
The Invitation Link is set to never expire and still works (just tested).

Here is another invite link valid for 7 days: https://discord.gg/hSZyCFAZ

**Comment by raimannma** [comment]
Alternativly send me a friend request on discord: "manuelhexe"

**Comment by Kosty1024Bit** [comment]
Unfortunately, this did not help(
Is there any other way I can get the key?
![1](https://github.com/user-attachments/assets/6b1534cd-75b8-46ce-aa57-00caa4ebafaf)
